namespace EggMapper.Generator
{
    /// <summary>
    /// Attribute source code injected into every compilation that references EggMapper.Generator.
    /// This avoids requiring a separate EggMapper.Abstractions runtime package — the attributes
    /// are generated directly into the user's project.
    /// </summary>
    internal static class AttributeSource
    {
        public const string MapToAttribute = @"// <auto-generated/>
#nullable enable
using System;

namespace EggMapper
{
    /// <summary>
    /// Instructs EggMapper.Generator to generate a compile-time extension method
    /// <c>source.ToTDestination()</c> and <c>IEnumerable&lt;TSource&gt;.ToTDestinationList()</c>.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
    internal sealed class MapToAttribute : Attribute
    {
        public Type DestinationType { get; }
        public MapToAttribute(Type destinationType)
            => DestinationType = destinationType ?? throw new ArgumentNullException(nameof(destinationType));
    }
}
";

        public const string MapPropertyAttribute = @"// <auto-generated/>
#nullable enable
using System;

namespace EggMapper
{
    /// <summary>
    /// Overrides the default by-name property matching: maps this source property to
    /// the named destination member instead.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = true)]
    internal sealed class MapPropertyAttribute : Attribute
    {
        public string DestinationMember { get; }
        public MapPropertyAttribute(string destinationMember)
            => DestinationMember = destinationMember ?? throw new ArgumentNullException(nameof(destinationMember));
    }
}
";

        public const string MapIgnoreAttribute = @"// <auto-generated/>
#nullable enable
using System;

namespace EggMapper
{
    /// <summary>
    /// Instructs EggMapper.Generator to skip this source property in the generated mapping.
    /// The corresponding destination property will remain at its default value.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = true)]
    internal sealed class MapIgnoreAttribute : Attribute { }
}
";
    }
}
