namespace EggMapper.ClassMapper
{
    internal static class AttributeSource
    {
        public const string Code = @"
// <auto-generated/>
using System;

namespace EggMapper
{
    /// <summary>
    /// Marks a <c>partial</c> class as an EggMapper mapper class.
    /// The source generator will implement all declared <c>partial</c> mapping
    /// methods, matching properties by name and emitting zero-overhead assignments.
    /// </summary>
    /// <example>
    /// <code>
    /// [EggMapper]
    /// public partial class OrderMapper
    /// {
    ///     public partial OrderDto Map(Order source);
    ///     public partial Order Map(OrderDto source);  // reverse
    /// }
    /// </code>
    /// </example>
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class EggMapperAttribute : Attribute { }
}
";
    }
}
