using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EggMapper.ClassMapper
{
    [Generator]
    public sealed class ClassMapperGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Inject [EggMapper] attribute into every compilation that references this generator.
            context.RegisterPostInitializationOutput(static ctx =>
                ctx.AddSource("EggMapperAttribute.g.cs",
                    SourceText.From(AttributeSource.Code, Encoding.UTF8)));

            // Find all partial classes annotated with [EggMapper].
            var pipeline = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "EggMapper.EggMapperAttribute",
                    predicate: static (node, _) =>
                        node is ClassDeclarationSyntax cls &&
                        cls.Modifiers.Any(SyntaxKind.PartialKeyword),
                    transform: static (ctx, ct) => Generate(ctx, ct))
                .Where(static r => r is not null);

            context.RegisterSourceOutput(pipeline, static (ctx, result) =>
            {
                foreach (var diag in result!.Diagnostics)
                    ctx.ReportDiagnostic(diag);

                if (result.Source is not null)
                    ctx.AddSource(result.HintName,
                        SourceText.From(result.Source, Encoding.UTF8));
            });
        }

        // ─── Main transform ───────────────────────────────────────────────────────

        private static GenerationResult? Generate(
            GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return null;
            ct.ThrowIfCancellationRequested();

            var diags = ImmutableArray.CreateBuilder<Diagnostic>();

            // Collect partial method *definitions* (no body, non-void, single param).
            var partialMethods = ImmutableArray.CreateBuilder<IMethodSymbol>();
            foreach (var m in classSymbol.GetMembers())
            {
                if (m is IMethodSymbol ms &&
                    ms.IsPartialDefinition &&
                    !ms.ReturnsVoid &&
                    ms.Parameters.Length == 1)
                    partialMethods.Add(ms);
            }

            if (partialMethods.Count == 0)
            {
                diags.Add(Diagnostic.Create(
                    Diagnostics.NoMappingMethodsDeclared,
                    ctx.TargetNode.GetLocation(),
                    classSymbol.Name));
                return new GenerationResult(HintName(classSymbol), null, diags.ToImmutable());
            }

            // Collect user-defined converter methods (ordinary, non-partial, 1 param, non-void).
            var converters = ImmutableArray.CreateBuilder<IMethodSymbol>();
            foreach (var m in classSymbol.GetMembers())
            {
                if (m is IMethodSymbol ms &&
                    ms.MethodKind == MethodKind.Ordinary &&
                    !ms.IsPartialDefinition &&
                    !ms.IsAbstract &&
                    ms.Parameters.Length == 1 &&
                    !ms.ReturnsVoid)
                    converters.Add(ms);
            }

            var methods = partialMethods.ToImmutable();
            var convs = converters.ToImmutable();

            // ── Build source ──────────────────────────────────────────────────────
            var ns = classSymbol.ContainingNamespace is { IsGlobalNamespace: false } nsym
                ? nsym.ToDisplayString() : null;
            var access = classSymbol.DeclaredAccessibility == Accessibility.Public
                ? "public" : "internal";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();

            int depth = 0;
            if (ns is not null)
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
                depth = 1;
            }

            string i1 = Indent(depth);
            string i2 = Indent(depth + 1);
            string i3 = Indent(depth + 2);
            string i4 = Indent(depth + 3);

            sb.AppendLine($"{i1}{access} partial class {classSymbol.Name}");
            sb.AppendLine($"{i1}{{");
            sb.AppendLine($"{i2}/// <summary>Singleton instance — use for dependency-injection scenarios.</summary>");
            sb.AppendLine($"{i2}public static {classSymbol.Name} Instance {{ get; }} = new {classSymbol.Name}();");

            foreach (var method in methods)
            {
                ct.ThrowIfCancellationRequested();
                sb.AppendLine();
                EmitMethod(sb, method, methods, convs, diags, i2, i3, i4);
            }

            sb.AppendLine($"{i1}}}");
            if (ns is not null) sb.AppendLine("}");

            return new GenerationResult(HintName(classSymbol), sb.ToString(), diags.ToImmutable());
        }

        // ─── Method generation ────────────────────────────────────────────────────

        private static void EmitMethod(
            StringBuilder sb,
            IMethodSymbol method,
            ImmutableArray<IMethodSymbol> allPartials,
            ImmutableArray<IMethodSymbol> converters,
            ImmutableArray<Diagnostic>.Builder diags,
            string i2, string i3, string i4)
        {
            var srcType = method.Parameters[0].Type;
            var dstType = method.ReturnType as INamedTypeSymbol;
            if (dstType is null) return;

            string ma = AccessStr(method.DeclaredAccessibility);
            string srcName = srcType.ToDisplayString();
            string dstName = dstType.ToDisplayString();
            string param = method.Parameters[0].Name;

            sb.AppendLine($"{i2}{ma} partial {dstName} {method.Name}({srcName} {param})");
            sb.AppendLine($"{i2}{{");
            sb.AppendLine($"{i3}if ({param} is null) throw new ArgumentNullException(nameof({param}));");
            sb.AppendLine($"{i3}return new {dstName}");
            sb.AppendLine($"{i3}{{");

            var dstProps = WritableProps(dstType);
            var srcProps = ReadableProps(srcType);

            // Index source props case-insensitively by name for fast lookup.
            var srcIndex = new System.Collections.Generic.Dictionary<string, IPropertySymbol>(
                System.StringComparer.OrdinalIgnoreCase);
            foreach (var p in srcProps)
                srcIndex[p.Name] = p;

            foreach (var dp in dstProps)
            {
                if (!srcIndex.TryGetValue(dp.Name, out var sp))
                {
                    diags.Add(Diagnostic.Create(
                        Diagnostics.UnmappedDestinationProperty,
                        method.Locations.IsEmpty ? Location.None : method.Locations[0],
                        dp.Name, dstType.Name, srcType.Name));
                    sb.AppendLine($"{i4}// EGG3001: no source for '{dp.Name}'");
                    continue;
                }

                var assignment = ResolveAssignment(
                    sp, dp, param, allPartials, converters, diags, method);
                sb.AppendLine($"{i4}{dp.Name} = {assignment},");
            }

            sb.AppendLine($"{i3}}};");
            sb.AppendLine($"{i2}}}");
        }

        // ─── Assignment resolution ────────────────────────────────────────────────

        private static string ResolveAssignment(
            IPropertySymbol sp,
            IPropertySymbol dp,
            string param,
            ImmutableArray<IMethodSymbol> allPartials,
            ImmutableArray<IMethodSymbol> converters,
            ImmutableArray<Diagnostic>.Builder diags,
            IMethodSymbol containingMethod)
        {
            var st = sp.Type;
            var dt = dp.Type;
            string expr = $"{param}.{sp.Name}";

            // 1. User-defined converter method: TSource → TDest.
            foreach (var conv in converters)
            {
                if (TypesMatch(conv.Parameters[0].Type, st) &&
                    TypesMatch(conv.ReturnType, dt))
                    return $"{conv.Name}({expr})";
            }

            // 2. Exact same type (ignoring nullability annotation).
            if (TypesMatch(st, dt))
                return expr;

            // 3. Enum-to-enum cast.
            if (st.TypeKind == TypeKind.Enum && dt.TypeKind == TypeKind.Enum)
            {
                // Warn if underlying types differ.
                if (st is INamedTypeSymbol sne && dt is INamedTypeSymbol dne &&
                    !TypesMatch(sne.EnumUnderlyingType!, dne.EnumUnderlyingType!))
                {
                    diags.Add(Diagnostic.Create(
                        Diagnostics.EnumUnderlyingTypeMismatch,
                        containingMethod.Locations.IsEmpty
                            ? Location.None : containingMethod.Locations[0],
                        st.Name, dt.Name));
                }
                return $"({dt.ToDisplayString()}){expr}";
            }

            // 4. Numeric widening / narrowing: emit explicit cast.
            if (IsNumeric(st) && IsNumeric(dt))
                return $"({dt.ToDisplayString()}){expr}";

            // 5. Another partial method maps st → dt.
            foreach (var pm in allPartials)
            {
                if (TypesMatch(pm.Parameters[0].Type, st) &&
                    TypesMatch(pm.ReturnType, dt))
                    return $"{pm.Name}({expr})";
            }

            // 6. Collection: IEnumerable<TSrc> → List<TDst> (if TSrc maps to TDst).
            if (TryCollectionAssignment(
                    st, dt, expr, allPartials, converters, out var colExpr))
                return colExpr!;

            // Fallback: direct cast — will produce a compile error if truly incompatible,
            // but at least shows the user what failed.
            return $"({dt.ToDisplayString()}){expr} /* incompatible types */";
        }

        private static bool TryCollectionAssignment(
            ITypeSymbol st,
            ITypeSymbol dt,
            string srcExpr,
            ImmutableArray<IMethodSymbol> allPartials,
            ImmutableArray<IMethodSymbol> converters,
            out string? expr)
        {
            expr = null;

            if (dt is not INamedTypeSymbol dtn || st is not INamedTypeSymbol stn)
                return false;

            if (!IsListLike(dtn) || dtn.TypeArguments.Length != 1) return false;

            ITypeSymbol? srcElem = GetEnumerableElement(stn);
            if (srcElem is null) return false;

            ITypeSymbol dstElem = dtn.TypeArguments[0];
            string dstElemName = dstElem.ToDisplayString();

            // Same element type — simple .ToList().
            if (TypesMatch(srcElem, dstElem))
            {
                expr = $"{srcExpr}?.ToList() ?? new List<{dstElemName}>()";
                return true;
            }

            // Enum-to-enum element mapping.
            if (srcElem.TypeKind == TypeKind.Enum && dstElem.TypeKind == TypeKind.Enum)
            {
                expr = $"{srcExpr}?.Select(x => ({dstElemName})x).ToList() " +
                       $"?? new List<{dstElemName}>()";
                return true;
            }

            // Converter or partial method for element type.
            foreach (var conv in converters)
            {
                if (TypesMatch(conv.Parameters[0].Type, srcElem) &&
                    TypesMatch(conv.ReturnType, dstElem))
                {
                    expr = $"{srcExpr}?.Select({conv.Name}).ToList() " +
                           $"?? new List<{dstElemName}>()";
                    return true;
                }
            }

            foreach (var pm in allPartials)
            {
                if (TypesMatch(pm.Parameters[0].Type, srcElem) &&
                    TypesMatch(pm.ReturnType, dstElem))
                {
                    expr = $"{srcExpr}?.Select({pm.Name}).ToList() " +
                           $"?? new List<{dstElemName}>()";
                    return true;
                }
            }

            return false;
        }

        // ─── Symbol helpers ───────────────────────────────────────────────────────

        private static bool TypesMatch(ITypeSymbol a, ITypeSymbol b) =>
            SymbolEqualityComparer.Default.Equals(
                a.WithNullableAnnotation(NullableAnnotation.None),
                b.WithNullableAnnotation(NullableAnnotation.None));

        private static bool IsNumeric(ITypeSymbol t) =>
            t.SpecialType is
                SpecialType.System_Byte or SpecialType.System_SByte or
                SpecialType.System_Int16 or SpecialType.System_UInt16 or
                SpecialType.System_Int32 or SpecialType.System_UInt32 or
                SpecialType.System_Int64 or SpecialType.System_UInt64 or
                SpecialType.System_Single or SpecialType.System_Double or
                SpecialType.System_Decimal;

        private static bool IsListLike(INamedTypeSymbol t)
        {
            var orig = t.OriginalDefinition.ToDisplayString();
            return orig is
                "System.Collections.Generic.List<T>" or
                "System.Collections.Generic.IList<T>" or
                "System.Collections.Generic.ICollection<T>" or
                "System.Collections.Generic.IReadOnlyList<T>" or
                "System.Collections.Generic.IReadOnlyCollection<T>";
        }

        private static ITypeSymbol? GetEnumerableElement(INamedTypeSymbol t)
        {
            // Direct generic with 1 type arg on a well-known collection.
            if (t.TypeArguments.Length == 1 &&
                t.OriginalDefinition.ToDisplayString() is
                    "System.Collections.Generic.IEnumerable<T>" or
                    "System.Collections.Generic.List<T>" or
                    "System.Collections.Generic.IList<T>" or
                    "System.Collections.Generic.ICollection<T>" or
                    "System.Collections.Generic.IReadOnlyList<T>" or
                    "System.Collections.Generic.IReadOnlyCollection<T>")
                return t.TypeArguments[0];

            // Walk interfaces to find IEnumerable<T>.
            foreach (var iface in t.AllInterfaces)
            {
                if (iface.OriginalDefinition.SpecialType ==
                    SpecialType.System_Collections_Generic_IEnumerable_T &&
                    iface.TypeArguments.Length == 1)
                    return iface.TypeArguments[0];
            }
            return null;
        }

        private static ImmutableArray<IPropertySymbol> WritableProps(INamedTypeSymbol type)
        {
            var b = ImmutableArray.CreateBuilder<IPropertySymbol>();
            foreach (var m in type.GetMembers())
            {
                if (m is IPropertySymbol p &&
                    !p.IsStatic && !p.IsIndexer &&
                    p.GetMethod != null && p.SetMethod != null)
                    b.Add(p);
            }
            return b.ToImmutable();
        }

        private static ImmutableArray<IPropertySymbol> ReadableProps(ITypeSymbol type)
        {
            var b = ImmutableArray.CreateBuilder<IPropertySymbol>();
            // Include base class properties.
            for (var t = type; t is not null && t.SpecialType != SpecialType.System_Object; t = t.BaseType)
            {
                foreach (var m in t.GetMembers())
                {
                    if (m is IPropertySymbol p && !p.IsStatic && !p.IsIndexer && p.GetMethod != null)
                        b.Add(p);
                }
            }
            return b.ToImmutable();
        }

        // ─── Utilities ────────────────────────────────────────────────────────────

        private static string HintName(INamedTypeSymbol cls) => $"{cls.Name}.g.cs";

        private static string Indent(int depth) => new string(' ', depth * 4);

        private static string AccessStr(Accessibility a) => a switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "private"
        };
    }

    // ─── Result record ────────────────────────────────────────────────────────────

    internal sealed class GenerationResult
    {
        public string HintName { get; }
        public string? Source { get; }
        public ImmutableArray<Diagnostic> Diagnostics { get; }

        public GenerationResult(string hintName, string? source,
            ImmutableArray<Diagnostic> diagnostics)
        {
            HintName = hintName;
            Source = source;
            Diagnostics = diagnostics;
        }
    }
}
